stages:
  - build_assets
  - build_content
  - deploy

assets:
  image: node
  stage: build_assets
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - source
    expire_in: 1 day
  script:
    - yarn install
    - yarn run prod

content:
  image: composer
  stage: build_content
  cache:
    paths:
      - vendor
  artifacts:
    paths:
      - output_prod
    expire_in: 1 day
  script:
    - composer install
    - php vendor/bin/sculpin generate -e prod

pages:
  image: alpine
  stage: deploy
  script:
    - mv output_prod public
  artifacts:
    paths:
      - public
  only:
    - master
