services:
  DragoonBoots\DanKeenanSiteBundle\TwigExtension\DanKeenanExtension:
    tags:
      - twig.extension
  
  # Symfony services
  # In a full Symfony app, these are exposed with certain bundles.  Because
  # those are not available in this context, expose them manually.
#  cache.system:
#    class: Symfony\Component\Cache\Adapter\NullAdapter
#  assets.packages:
#    class: Symfony\Component\Asset\Packages
#  twig.extension.assets:
#    class: Symfony\Bridge\Twig\Extension\AssetExtension
#    arguments:
#      - '@assets.packages'
#    tags:
#      - twig.extension
